config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'contacts#index'
  resources :csv_files, only: %i[index new create]
  resources :contacts, only: %i[index]
  resources :contact_logs, only: %i[index]
end

app/views/shared/_nav.html.erb
<div class="container-fluid" >
<%
  if user_signed_in?

  %>
<h3>
  <p>
Welcome!    <%=  user_signed_in? ? (current_user.email) : ''%>
  </p>
</h3>
<div class="card mb-3"> <div class="card-body">
    <p class="card-text">Contacts imported: <%= stats[:contacts_count] %>
Failed contacts imported: <%= stats[:contacts_failed_count] %>
</p>
<p class="card-text">CsvFiles
[On Hold: <%= stats[:csv_on_hold] %>
Processing: <%= stats[:csv_processing] %>
Finished: <%= stats[:csv_finished] %>
Failed: <%= stats[:csv_failed] %> ]
</p>
  </div>
</div>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Contacts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Show imported", contacts_path, class: 'dropdown-item' %></li>
            <li><%= link_to "Show Failed", contact_logs_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Csv Files
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Show",csv_files_path, class: 'dropdown-item' %></li>
            <li><%= link_to "New", new_csv_file_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, class:"nav-link",  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<%
  end
%>

</div>